meta_product_name: "MELJ CENTER"
meta_title: "Effecting Change & Opportunity for All"
meta_description: "MELJ CENTER MAKES THE FORMERLY INCARCERATED REINTEGRATION POSITIVE - SUPPORTIVE - ELIMINATING NEGATIVE BARRIERS FOR SUCCESS!"
meta_image: "melj_banner_og.png" # should exist in `app/assets/images/`
